# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='amount_raised',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feeditem',
            name='goal_raised',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
            preserve_default=False,
        ),
    ]
