# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_feed', '0002_auto_20160623_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='img_url',
            field=models.URLField(default=''),
        ),
    ]
